const mapElement=document.querySelector('#thailand-map');
let activeBranchMap=null,branchCleanup=null,lastUserLocation=null;
function initializeBranchMap(){
 if(!mapElement||!window.L)return;
 branchCleanup?.();activeBranchMap?.remove();document.querySelector('#branch-route')?.remove();
 const points=JSON.parse(document.querySelector('#branch-points').textContent),bounds=L.latLngBounds([[5.6,97.3],[20.6,105.7]]);
 const map=L.map(mapElement,{scrollWheelZoom:true,maxBounds:bounds.pad(.08),maxBoundsViscosity:1,zoomSnap:.25});activeBranchMap=map;map.attributionControl.addAttribution('Routes: <a href="https://project-osrm.org">OSRM</a>');
 const overview=()=>{map.setMinZoom(0);map.fitBounds(bounds,{padding:[12,12]});map.setMinZoom(map.getZoom());};
 L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
 const box=el('section',null,'route-box');box.id='branch-route';const title=el('h3','วางแผนไปสาขา'),result=el('p','เลือกสาขาจากหมุดหรือรายการด้านข้าง'),note=el('p','เมื่อกดหาสาขาใกล้ฉัน ระบบจะส่งตำแหน่งให้ OSRM เพื่อคำนวณเส้นทาง ไม่บันทึกตำแหน่งของคุณไว้','route-attribution');
 const label=el('label','จุดเริ่มต้นอื่น (ไม่บังคับ)'),start=el('input');start.placeholder='เช่น อนุสาวรีย์ชัยสมรภูมิ';label.append(start);const modes=el('label','เดินทางด้วย'),mode=el('select');for(const [value,text] of [['driving','รถยนต์'],['transit','ขนส่งสาธารณะ'],['walking','เดิน']]){const o=el('option',text);o.value=value;mode.append(o);}modes.append(mode);
 const actions=el('div',null,'route-actions'),google=el('a','คำนวณ / นำทางใน Google Maps ↗','button primary'),locate=el('button','ใช้ตำแหน่งของฉัน','button outline');google.target='_blank';google.rel='noopener';actions.append(google,locate);const attribution=el('p',null,'route-attribution');const source=el('a','เส้นทางโดย OSRM');source.href='https://project-osrm.org';source.target='_blank';source.rel='noopener';attribution.append(source,document.createTextNode(' · ข้อมูล OpenStreetMap · เวลาโดยประมาณ ไม่รวมรถติด'));const manual=el('details'),summary=el('summary','เลือกจุดเริ่มต้นหรือวิธีเดินทางเอง');manual.append(summary,label,modes);box.append(title,result,actions,manual);document.querySelector('.locations-layout').before(box);
 let selected=null,userMarker=null,line=null,controller=null,request=0,routeTimer,popupTimer,resizeTimer;const cache=new Map();
 function googleURL(){if(selected===null){google.hidden=true;return;}google.hidden=false;const url=new URL('https://www.google.com/maps/dir/');url.searchParams.set('api','1');url.searchParams.set('destination',points[selected].coordinates.join(','));url.searchParams.set('travelmode',mode.value);const origin=start.value.trim()||(lastUserLocation?lastUserLocation.join(','):'');if(origin)url.searchParams.set('origin',origin);google.href=url.href;}
 function clearRoute(){controller?.abort();request++;clearTimeout(routeTimer);if(line){map.removeLayer(line);line=null;}}
 async function calculate(){if(selected===null||!lastUserLocation||start.value.trim()||mode.value!=='driving')return;const index=selected,id=++request,from=lastUserLocation.slice(),to=points[index].coordinates,key=from.join(',')+';'+to.join(',');controller?.abort();controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),10000);result.textContent='กำลังคำนวณเส้นทางขับรถ…';try{let route=cache.get(key);if(!route){const coordinates=[from,to].map(([lat,lng])=>lng+','+lat).join(';');const response=await fetch('https://router.project-osrm.org/route/v1/driving/'+coordinates+'?overview=full&geometries=geojson&steps=false',{signal:controller.signal});if(!response.ok)throw Error();const data=await response.json();route=data.code==='Ok'?data.routes?.[0]:null;if(!route||!Number.isFinite(route.distance)||!Number.isFinite(route.duration)||route.geometry?.type!=='LineString')throw Error();cache.set(key,route);}if(id!==request||selected!==index)return;if(line)map.removeLayer(line);line=L.geoJSON(route.geometry,{style:{color:'#234be4',weight:5,opacity:.85}}).addTo(map);map.fitBounds(line.getBounds(),{padding:[35,35],maxZoom:14});const minutes=Math.ceil(route.duration/60),time=minutes>=60?Math.floor(minutes/60)+' ชม. '+minutes%60+' นาที':minutes+' นาที';result.textContent=`ไป ${points[index].name} · ${(route.distance/1000).toLocaleString('th-TH',{maximumFractionDigits:1})} กม. · ประมาณ ${time}`;}catch{if(id===request)result.textContent='คำนวณในแผนที่ไม่สำเร็จ กด Google Maps เพื่อคำนวณและนำทางได้เลย';}finally{clearTimeout(timeout);}}
 function selectRoute(index){clearRoute();selected=index;title.textContent='เส้นทางไป '+points[index].name;googleURL();result.textContent=lastUserLocation?'กำลังเตรียมเส้นทาง…':'กดใช้ตำแหน่งของฉัน หรือกรอกจุดเริ่มต้นแล้วเปิด Google Maps';if(lastUserLocation)routeTimer=setTimeout(calculate,450);}
 const closePopup=()=>{clearTimeout(popupTimer);popupTimer=setTimeout(()=>map.closePopup(),350);};
 const markers=points.map((p,index)=>{const content=el('div'),img=el('img',null,'branch-popup-photo');img.src=p.image;img.alt=p.name;const link=el('button','คำนวณเส้นทางไปสาขานี้','map-route-button');link.type='button';link.onclick=()=>selectRoute(index);content.append(img,el('strong',p.name),el('p',p.address),link);content.onmouseenter=()=>clearTimeout(popupTimer);content.onmouseleave=closePopup;const marker=L.circleMarker(p.coordinates,{radius:8,color:'white',weight:2,fillColor:'#ef454c',fillOpacity:1}).addTo(map).bindPopup(content,{maxWidth:280,autoPan:false});if(matchMedia('(hover:hover)').matches){marker.on('mouseover',()=>{clearTimeout(popupTimer);marker.openPopup();});marker.on('mouseout',closePopup);}marker.on('click',()=>choose(index));return marker;});
 function choose(index){map.setView(points[index].coordinates,15);markers[index].openPopup();document.querySelectorAll('[data-branch]').forEach(button=>button.setAttribute('aria-pressed',String(Number(button.dataset.branch)===index)));selectRoute(index);}
 document.querySelectorAll('[data-branch]').forEach(button=>button.onclick=()=>{choose(Number(button.dataset.branch));if(innerWidth<850)mapElement.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});});
 const overviewButton=document.querySelector('[data-map-overview]');overviewButton.onclick=()=>{clearRoute();map.closePopup();overview();document.querySelectorAll('[data-branch]').forEach(b=>b.setAttribute('aria-pressed','false'));};
 const locateButton=document.querySelector('#find-nearest'),locationStatus=document.querySelector('#location-status');locationStatus.textContent='';
 function showUser(){if(userMarker)map.removeLayer(userMarker);if(lastUserLocation&&bounds.contains(lastUserLocation))userMarker=L.circleMarker(lastUserLocation,{radius:9,color:'white',weight:3,fillColor:'#173cc0',fillOpacity:1}).addTo(map).bindTooltip('ตำแหน่งของคุณ');}
 const locateUser=(destination=null)=>{if(!navigator.geolocation||!isSecureContext){locationStatus.textContent='ใช้ตำแหน่งไม่ได้ กรอกจุดเริ่มต้นในช่องเส้นทางได้เลย';return;}locateButton.disabled=true;locate.disabled=true;locationStatus.textContent='กำลังหาตำแหน่ง กรุณาอนุญาตในเบราว์เซอร์';navigator.geolocation.getCurrentPosition(position=>{lastUserLocation=[position.coords.latitude,position.coords.longitude];start.value='';showUser();const distances=points.map(p=>L.latLng(lastUserLocation).distanceTo(L.latLng(p.coordinates))),nearest=distances.indexOf(Math.min(...distances));choose(destination===null?nearest:destination);locationStatus.textContent=destination!==null?'กำลังคำนวณไป '+points[destination].name:'ใกล้ที่สุดตามระยะเส้นตรง: '+points[nearest].name+' · เลือกสาขาอื่นเพื่อเปรียบเทียบเส้นทางได้';locateButton.disabled=false;locate.disabled=false;},error=>{locationStatus.textContent=error.code===1?'ไม่ได้อนุญาตตำแหน่ง กรอกจุดเริ่มต้นแล้วเปิด Google Maps ได้':'ยังหาตำแหน่งไม่ได้ ลองอีกครั้งหรือกรอกจุดเริ่มต้น';locateButton.disabled=false;locate.disabled=false;},{enableHighAccuracy:false,timeout:12000,maximumAge:60000});};
 locateButton.onclick=()=>locateUser();locate.onclick=()=>locateUser(selected);start.oninput=()=>{clearRoute();googleURL();result.textContent=start.value.trim()?'กด Google Maps เพื่อคำนวณจากจุดเริ่มต้นที่กรอก':'กดใช้ตำแหน่งของฉันเพื่อแสดงเส้นทาง';if(!start.value.trim()&&lastUserLocation)routeTimer=setTimeout(calculate,450);};mode.onchange=()=>{clearRoute();googleURL();result.textContent=mode.value==='driving'?'กำลังเตรียมเส้นทาง…':'กด Google Maps เพื่อคำนวณการเดินทางแบบที่เลือก';if(mode.value==='driving')calculate();};googleURL();overview();showUser();
 const resize=()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>map.invalidateSize(),150);};window.addEventListener('resize',resize);branchCleanup=()=>{clearRoute();clearTimeout(popupTimer);clearTimeout(resizeTimer);window.removeEventListener('resize',resize);};
}
initializeBranchMap();document.addEventListener('gdd:branches-updated',initializeBranchMap);
