(() => {
 const root=new URL('.',document.currentScript.src),article=document.querySelector('#course-record');let last='';
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
 const imageURL=value=>typeof value==='string'&&/^(assets\/|data:image\/(png|jpeg|webp);base64,)/.test(value)?(value.startsWith('data:')?value:new URL(value,root).href):null;
 const safeLink=value=>{try{const u=new URL(value,root);return /^https?:$/.test(u.protocol)?u.href:null;}catch{return null;}};
 const youtube=value=>{try{const u=new URL(value);const id=u.hostname==='youtu.be'?u.pathname.slice(1):['www.youtube.com','youtube.com','www.youtube-nocookie.com','youtube-nocookie.com'].includes(u.hostname)?u.searchParams.get('v')||u.pathname.match(/\/(?:embed|shorts)\/([\w-]+)/)?.[1]:null;return /^[\w-]{11}$/.test(id||'')?'https://www.youtube-nocookie.com/embed/'+id:null;}catch{return null;}};
 function photo(value,title){const src=imageURL(value);if(!src)return null;const img=el('img');img.src=src;img.alt=title;img.loading='lazy';return img;}
 function courseCard(c){const a=el('a',null,'course-card');a.href=new URL('courses/article/index.html?id='+encodeURIComponent(c.id),root);a.dataset.category=c.category;const top=el('div',null,'course-top');top.append(el('span',c.title.slice(0,1),'course-symbol'),el('span',c.category,'small-label'));a.append(top,el('h3',c.title),el('p',c.summary));const bottom=el('div',null,'course-bottom');bottom.append(el('span',c.category),el('span','รายละเอียดคอร์ส','text-link'));a.append(bottom);return a;}
 function galleryCard(item){if(item.kind==='photo'){const button=el('button',null,'gallery-item'),img=photo(item.image,item.title);if(img)button.append(img);button.dataset.recordId=item.id;button.setAttribute('aria-label','ขยายภาพ '+item.title);button.onclick=()=>{const dialog=document.querySelector('#lightbox');if(!dialog)return;dialog.querySelector('img').src=imageURL(item.image);dialog.querySelector('img').alt=item.title;dialog.querySelector('p').textContent=item.title;dialog.showModal();};return button;}const card=el('article',null,item.kind==='video'?'video-card':'news-card');card.dataset.recordId=item.id;if(item.kind==='video'){const src=youtube(item.url||item.image);if(src){const frame=el('div',null,'video-frame'),iframe=el('iframe');iframe.src=src;iframe.title=item.title;iframe.loading='lazy';iframe.allowFullscreen=true;frame.append(iframe);card.append(frame);}}else{const img=photo(item.image,item.title);if(img)card.append(img);}const copy=el('div',null,'card-copy');copy.append(el('h3',item.title),el('p',item.body));const url=safeLink(item.url);if(url&&item.url){const a=el('a',item.kind==='video'?'ดูบน YouTube':'ดูผลงาน','text-link');a.href=url;a.target='_blank';a.rel='noopener';copy.append(a);}card.append(copy);return card;}
 
 function repeating(data){
 const carousel=document.querySelector('.hero-carousel');if(carousel&&data.slides){carousel.querySelectorAll('[data-slide]').forEach(n=>n.remove());const dots=carousel.querySelector('.carousel-dots');dots.replaceChildren();data.slides.filter(r=>r.published!==false&&imageURL(r.image)).forEach((r,i)=>{const slide=el('div',null,'hero-slide');slide.dataset.slide=i;slide.dataset.recordId=r.id;const img=photo(r.image,r.title);img.loading='eager';slide.append(img);carousel.prepend(slide);const dot=el('button');dot.type='button';dot.dataset.goTo=i;dot.setAttribute('aria-label','รูป '+(i+1));dots.append(dot);});document.dispatchEvent(new Event('gdd:slides-updated'));}
 const list=document.querySelector('.branch-list'),script=document.querySelector('#branch-points');if(list&&script&&data.branches){const points=data.branches.filter(r=>r.published!==false).map(r=>({...r,name:r.title,image:imageURL(r.image)||'',coordinates:r.coordinates}));list.replaceChildren(...points.map((r,i)=>{const card=el('article',null,'branch-card');card.dataset.recordId=r.id;const img=el('img');if(r.image){img.src=r.image;img.alt=r.title;img.loading='lazy';img.className='branch-photo';card.append(img);}const copy=el('div',null,'branch-details'),button=el('button',null,'branch-select');button.dataset.branch=i;button.setAttribute('aria-pressed','false');button.append(el('span',String(i+1),'branch-number'),el('span',r.title));copy.append(button,el('p',r.address));if(r.url&&safeLink(r.url)){const link=el('a','เปิด Google Maps','text-link');link.href=safeLink(r.url);link.target='_blank';link.rel='noopener';copy.append(link);}card.append(copy);return card;}));script.dataset.collectionOwned='true';script.textContent=JSON.stringify(points);document.dispatchEvent(new Event('gdd:branches-updated'));}
 const awards=document.querySelector('.award-grid');if(awards&&data.awards){awards.replaceChildren(...data.awards.filter(r=>r.published!==false).map(r=>{const card=el('article',null,'award-card');card.dataset.recordId=r.id;const img=photo(r.image,r.title),url=r.url&&safeLink(r.url);if(img){if(url){const a=el('a');a.href=url;a.append(img);card.append(a);}else card.append(img);}const copy=el('div',null,'card-copy');copy.append(el('span',r.category,'eyebrow'),el('h3',r.title),el('p',r.summary));card.append(copy);return card;}));}
 const filters=document.querySelector('.filters');if(filters&&data.courseCategories){const selected=filters.querySelector('[aria-pressed="true"]')?.dataset.filter||'ทั้งหมด';filters.replaceChildren(...['ทั้งหมด',...data.courseCategories].map(category=>{const b=el('button',category);b.dataset.filter=category;b.setAttribute('aria-pressed',String(category===selected));b.onclick=()=>{filters.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));let count=0;document.querySelectorAll('.course-card[data-category]').forEach(card=>{card.hidden=category!=='ทั้งหมด'&&card.dataset.category!==category;if(!card.hidden)count++;});document.querySelector('.result-count').textContent=count+' คอร์ส';};return b;}));}
 }
 function render(data){repeating(data);const courses=data.courses.filter(c=>c.published),gallery=data.gallery.filter(g=>g.published);if(article){const c=courses.find(c=>c.id===new URLSearchParams(location.search).get('id'));article.replaceChildren();const back=el('a','← คอร์สทั้งหมด','breadcrumb');back.href=new URL('courses/index.html',root);article.append(back);if(!c){article.append(el('h1','ไม่พบคอร์สนี้'));return;}document.title=c.title+' | GDD';article.append(el('span',c.category,'eyebrow'),el('h1',c.title),el('p',c.summary));const img=photo(c.image,c.title);if(img){img.className='course-poster';article.append(img);}article.append(el('div',c.body,'article-copy news-article-body'));for(const poster of c.posters||[]){if(!poster.image||poster.image===c.image)continue;const image=photo(poster.image,poster.title);if(image){article.append(el('h2',poster.title));image.className='course-poster';article.append(image);}}const ask=el('a','สอบถามคอร์สนี้','button primary');ask.href='https://page.line.me/gddcoding';ask.target='_blank';ask.rel='noopener';article.append(ask);return;}
  const grid=document.querySelector('.course-grid');if(grid){const home=location.pathname.endsWith('/index.html')&&grid.closest('#courses')===null&&!document.querySelector('[data-filter]');grid.replaceChildren(...(home?courses.filter(c=>c.featured).slice(0,3):courses).map(courseCard));const selected=document.querySelector('[data-filter][aria-pressed="true"]')?.dataset.filter||'ทั้งหมด';let count=0;grid.querySelectorAll('[data-category]').forEach(card=>{card.hidden=selected!=='ทั้งหมด'&&card.dataset.category!==selected;if(!card.hidden)count++;});if(home){const link=document.querySelector('.section-head a[href*="courses"]');if(link)link.textContent='ดูทั้ง '+courses.length+' คอร์ส';}const counter=document.querySelector('.result-count');if(counter)counter.textContent=count+' คอร์ส';}
  for(const [kind,selector] of [['photo','.gallery-grid'],['video','#videos .video-grid'],['work','#showcase .news-grid']]){const target=document.querySelector(selector);if(target)target.replaceChildren(...gallery.filter(g=>g.kind===kind).map(galleryCard));}
 }
 async function refresh(override){if(document.hidden&&!override?.courses)return;try{const data=override?.courses?override:await(await fetch(new URL('content/collections.json',root),{cache:'no-store'})).json();const raw=JSON.stringify(data);if(raw===last)return;last=raw;render(data);}catch{}}
 window.addEventListener('message',event=>{if(event.origin===location.origin&&event.source===parent&&parent!==window&&event.data?.type==='gdd-preview')refresh(event.data.collections).then(()=>{if(event.data.recordId){const node=document.querySelector('[data-record-id="'+event.data.recordId+'"]');node?.scrollIntoView({block:'center'});if(node?.dataset.slide)node.closest('.hero-carousel').querySelector('[data-go-to="'+node.dataset.slide+'"]')?.click();}});});
 refresh();if(!new URLSearchParams(location.search).has('editor-preview')){setInterval(refresh,15000);document.addEventListener('visibilitychange',refresh);}
})();
