(() => {
 const normalize = text => text.toLowerCase().normalize('NFKC').replace(/[^a-z0-9\u0e01-\u0e5b]/g,'').replace(/^(mrt|bts|เอ็มอาร์ที|บีทีเอส|สถานีรถไฟฟ้า|รถไฟฟ้า|สถานี)/,'').replace(/[\u0e31\u0e34-\u0e3a\u0e47-\u0e4e]/g,'');
 const places = [
  ['MRT ห้วยขวาง','huai khwang|huay kwang',[13.7786878,100.5735662]],
  ['MRT กำแพงเพชร','kamphaeng phet|กำแพง',[13.7979484,100.5478837]],
  ['BTS อนุสาวรีย์ชัยสมรภูมิ','victory monument',[13.7627589,100.5370529]],
  ['BTS พญาไท','phaya thai'],['BTS สยาม','siam'],['BTS อโศก','asok'],['BTS หมอชิต','mo chit'],['BTS ชิดลม','chit lom'],['BTS อารีย์','ari'],['BTS สะพานควาย','saphan khwai'],['BTS พร้อมพงษ์','phrom phong'],['BTS อ่อนนุช','on nut'],['BTS บางนา','bang na'],['BTS อุดมสุข','udom suk'],['BTS แบริ่ง','bearing'],['BTS สนามกีฬาแห่งชาติ','national stadium'],['BTS ศาลาแดง','sala daeng'],['BTS สะพานตากสิน','saphan taksin'],['MRT สุขุมวิท','sukhumvit'],['MRT พระราม 9','phra ram 9|rama 9'],['MRT ศูนย์วัฒนธรรมแห่งประเทศไทย','thailand cultural centre|ศูนย์วัฒนธรรม'],['MRT สุทธิสาร','sutthisan'],['MRT รัชดาภิเษก','ratchadaphisek'],['MRT ลาดพร้าว','lat phrao'],['MRT จตุจักร','chatuchak park|สวนจตุจักร'],['MRT เตาปูน','tao poon'],['MRT บางซื่อ','bang sue'],['MRT สามย่าน','sam yan'],['MRT สีลม','silom'],['MRT หัวลำโพง','hua lamphong'],['แฟชั่นไอส์แลนด์','fashion island|แฟชั่นไอแลนด์'],['เซ็นทรัลภูเก็ต','central phuket'],['สนามบินภูเก็ต','phuket airport']
 ].map(([name,aliases,coordinates])=>({name,aliases:aliases.split('|'),coordinates,local:true}));
 function distance(a,b){let row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const next=[i];for(let j=1;j<=b.length;j++)next[j]=Math.min(next[j-1]+1,row[j]+1,row[j-1]+(a[i-1]===b[j-1]?0:1));row=next;}return row[b.length];}
 function suggestions(query){const q=normalize(query);if(!q)return [];return places.map(place=>{const scores=[place.name,...place.aliases].map(name=>{const n=normalize(name);if(n===q)return 0;if(n.includes(q))return .1+(n.length-q.length)/100;const d=distance(q,n);return d<=Math.max(1,Math.min(3,Math.floor(n.length*.3)))?1+d/n.length:Infinity;});return {place,score:Math.min(...scores)};}).filter(x=>Number.isFinite(x.score)).sort((a,b)=>a.score-b.score).slice(0,5).map(x=>x.place);}
 const cache=new Map();
 window.attachPlaceSearch=(input,onSelect,getBias=()=>[13.7576494,100.5338292])=>{
  const el=(tag,text,cls)=>{const node=document.createElement(tag);if(text)node.textContent=text;if(cls)node.className=cls;return node;};
  const wrap=el('div',null,'place-search'),button=el('button','ค้นหาสถานที่','button outline'),list=el('ul',null,'place-suggestions'),status=el('p',null,'place-search-status');
  input.id='route-origin';input.autocomplete='off';input.setAttribute('role','combobox');input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-expanded','false');input.setAttribute('aria-controls','origin-suggestions');input.placeholder='พิมพ์ชื่อสถานี สถานที่ หรือที่อยู่';list.id='origin-suggestions';list.setAttribute('role','listbox');list.hidden=true;button.type='button';status.setAttribute('role','status');input.parentElement.htmlFor=input.id;input.parentElement.after(wrap);wrap.append(input,button,list,status);
  let timer,controller,request=0,rows=[],active=-1,composing=false;
  function hide(){list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');active=-1;}
  function show(items){rows=items;list.replaceChildren();active=-1;input.removeAttribute('aria-activedescendant');for(const [i,place] of items.entries()){const row=el('li');row.id='origin-option-'+i;row.setAttribute('role','option');row.setAttribute('aria-selected','false');const choose=el('button');choose.type='button';choose.tabIndex=-1;choose.append(el('strong',place.name));if(place.detail)choose.append(el('small',place.detail));choose.onclick=()=>select(place);row.append(choose);list.append(row);}list.hidden=!items.length;input.setAttribute('aria-expanded',String(!!items.length));}
  async function lookup(query,signal){const bias=getBias(),key=query.trim().toLowerCase()+';'+bias.join(',');if(cache.has(key))return cache.get(key);const url=new URL('https://photon.komoot.io/api/');url.searchParams.set('q',query.replace(/^(mrt|bts)\s*/i,''));url.searchParams.set('bbox','97.3,5.6,105.7,20.6');url.searchParams.set('limit','6');url.searchParams.set('lat',bias[0]);url.searchParams.set('lon',bias[1]);const response=await fetch(url,{signal});if(!response.ok)throw Error();const json=await response.json();const items=(json.features||[]).filter(f=>f.geometry?.type==='Point'&&f.geometry.coordinates?.length===2&&f.geometry.coordinates.every(Number.isFinite)&&f.properties?.name).map(f=>({name:f.properties.name,detail:[f.properties.osm_value==='station'?'สถานีรถไฟฟ้า':'',f.properties.city,f.properties.state].filter(Boolean).join(' · '),coordinates:[f.geometry.coordinates[1],f.geometry.coordinates[0]],station:f.properties.osm_value==='station'}));cache.set(key,items);return items;}
  async function search(){clearTimeout(timer);controller?.abort();const query=input.value.trim(),local=suggestions(query),id=++request;if(query.length<3){show(local);status.textContent='';return;}show(local);status.textContent=local.length?'เลือกสถานที่จากรายการด้านล่าง':'กำลังค้นหาสถานที่…';controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),8000);try{const remote=await lookup(local.length===1&&normalize(query).length>=5?local[0].name:query,controller.signal);if(id!==request)return;const seen=new Set(local.map(p=>normalize(p.name)));const merged=[...local];for(const place of remote){if(!seen.has(normalize(place.name))){merged.push(place);seen.add(normalize(place.name));}}show(merged.slice(0,6));status.textContent=merged.length?'เลือกสถานที่เพื่อใช้เป็นจุดเริ่มต้น':'ไม่พบสถานที่ ลองใช้ชื่อสถานีหรือชื่อสถานที่ใกล้เคียง';}catch{if(id===request)status.textContent=local.length?'เลือกชื่อที่แนะนำได้ หรือค้นหาต่อใน Google Maps':'ค้นหาไม่สำเร็จ ใช้ชื่อที่กรอกใน Google Maps ได้';}finally{clearTimeout(timeout);}}
  async function select(place){clearTimeout(timer);controller?.abort();const id=++request;input.value=place.name;hide();status.textContent='กำลังเลือกจุดเริ่มต้น…';try{let coordinates=place.coordinates;if(!coordinates){controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),8000);try{const matches=await lookup(place.name,controller.signal);coordinates=(matches.find(p=>p.station)||matches[0])?.coordinates;}finally{clearTimeout(timeout);}}if(id!==request)return;status.textContent=coordinates?'จุดเริ่มต้น: '+place.name:'เลือกชื่อสถานที่แล้ว เปิด Google Maps เพื่อนำทางได้';onSelect({name:place.name,coordinates:coordinates||null});}catch{if(id===request){status.textContent='เลือกชื่อสถานที่แล้ว เปิด Google Maps เพื่อนำทางได้';onSelect({name:place.name,coordinates:null});}}}
  function schedule(){controller?.abort();request++;clearTimeout(timer);show(suggestions(input.value));status.textContent='';if(!composing&&input.value.trim().length>=3)timer=setTimeout(search,700);}
  input.addEventListener('input',schedule);input.addEventListener('compositionstart',()=>{composing=true;clearTimeout(timer);});input.addEventListener('compositionend',()=>{composing=false;schedule();});input.addEventListener('focus',()=>{if(input.value.trim())show(suggestions(input.value));});
  input.addEventListener('keydown',event=>{if(event.isComposing)return;if(event.key==='Escape'){hide();return;}if(['ArrowDown','ArrowUp'].includes(event.key)&&rows.length&&!list.hidden){event.preventDefault();active=active<0?(event.key==='ArrowDown'?0:rows.length-1):(active+(event.key==='ArrowDown'?1:-1)+rows.length)%rows.length;[...list.children].forEach((row,i)=>row.setAttribute('aria-selected',String(i===active)));input.setAttribute('aria-activedescendant','origin-option-'+active);}else if(event.key==='Enter'){event.preventDefault();if(active>=0&&!list.hidden)select(rows[active]);else search();}});
  button.onclick=search;const outside=event=>{if(!wrap.contains(event.target))hide();};document.addEventListener('pointerdown',outside);
  return {search,clear(){request++;controller?.abort();clearTimeout(timer);input.value='';hide();status.textContent='';},dispose(){request++;controller?.abort();clearTimeout(timer);document.removeEventListener('pointerdown',outside);}};
 };
})();
