const menu=document.querySelector('.menu-toggle');
const navigation=document.querySelector('#navigation');
menu.addEventListener('click',()=>{const expanded=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!expanded));menu.setAttribute('aria-label',expanded?'เปิดเมนู':'ปิดเมนู');navigation.classList.toggle('open',!expanded);});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){navigation.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','เปิดเมนู');}});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));let count=0;document.querySelectorAll('[data-category]').forEach(card=>{const show=card.dataset.cmsHidden!=='true'&&(button.dataset.filter==='ทั้งหมด'||card.dataset.category===button.dataset.filter);card.hidden=!show;if(show)count++;});document.querySelector('.result-count').textContent=`${count} คอร์ส`;}));
const lightbox=document.querySelector('#lightbox');
document.querySelectorAll('[data-lightbox]').forEach(button=>button.addEventListener('click',()=>{const photo=lightbox.querySelector('img');photo.src=button.dataset.lightbox;photo.alt=button.dataset.caption;lightbox.querySelector('p').textContent=button.dataset.caption;lightbox.showModal();}));
lightbox.querySelector('.close-lightbox').addEventListener('click',()=>lightbox.close());
lightbox.addEventListener('click',event=>{if(event.target===lightbox){const bounds=lightbox.getBoundingClientRect();if(event.clientX<bounds.left||event.clientX>bounds.right||event.clientY<bounds.top||event.clientY>bounds.bottom)lightbox.close();}});

let carouselCleanup;
function setupCarousel(){carouselCleanup?.();const carousel=document.querySelector('.hero-carousel');if(!carousel)return;const slides=[...carousel.querySelectorAll('[data-slide]')].sort((a,b)=>Number(a.dataset.slide)-Number(b.dataset.slide)),dots=[...carousel.querySelectorAll('[data-go-to]')];let index=0,timer,touch;const listeners=[];const on=(target,name,fn)=>{target.addEventListener(name,fn);listeners.push(()=>target.removeEventListener(name,fn));};const schedule=()=>{clearTimeout(timer);if(slides.length>1&&!document.hidden&&!carousel.matches(':hover')&&!new URLSearchParams(location.search).has('editor-preview')&&!matchMedia('(prefers-reduced-motion:reduce)').matches)timer=setTimeout(()=>show(index+1),5000);};const show=n=>{if(!slides.length)return;index=(n+slides.length)%slides.length;slides.forEach((slide,i)=>{slide.hidden=false;slide.classList.toggle('is-active',i===index);slide.setAttribute('aria-hidden',String(i!==index));});dots.forEach((d,i)=>d.setAttribute('aria-current',String(i===index)));schedule();};on(carousel,'click',e=>{const b=e.target.closest('[data-go-to],[data-slide-step]');if(b)show(b.dataset.goTo!==undefined?Number(b.dataset.goTo):index+Number(b.dataset.slideStep));});on(carousel,'mouseenter',()=>clearTimeout(timer));on(carousel,'mouseleave',schedule);on(document,'visibilitychange',schedule);on(carousel,'touchstart',e=>{touch=e.changedTouches[0].clientX;clearTimeout(timer);});on(carousel,'touchend',e=>{const dx=e.changedTouches[0].clientX-touch;if(Math.abs(dx)>50)show(index+(dx<0?1:-1));else schedule();});carouselCleanup=()=>{clearTimeout(timer);listeners.forEach(fn=>fn());};show(0);}
setupCarousel();document.addEventListener('gdd:slides-updated',setupCarousel);
