const menu=document.querySelector('.menu-toggle');
const navigation=document.querySelector('#navigation');
menu.addEventListener('click',()=>{const expanded=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!expanded));menu.setAttribute('aria-label',expanded?'เปิดเมนู':'ปิดเมนู');navigation.classList.toggle('open',!expanded);});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){navigation.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','เปิดเมนู');}});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));let count=0;document.querySelectorAll('[data-category]').forEach(card=>{const show=card.dataset.cmsHidden!=='true'&&(button.dataset.filter==='ทั้งหมด'||card.dataset.category===button.dataset.filter);card.hidden=!show;if(show)count++;});document.querySelector('.result-count').textContent=`${count} คอร์ส`;}));
const lightbox=document.querySelector('#lightbox');
document.querySelectorAll('[data-lightbox]').forEach(button=>button.addEventListener('click',()=>{const photo=lightbox.querySelector('img');photo.src=button.dataset.lightbox;photo.alt=button.dataset.caption;lightbox.querySelector('p').textContent=button.dataset.caption;lightbox.showModal();}));
lightbox.querySelector('.close-lightbox').addEventListener('click',()=>lightbox.close());
lightbox.addEventListener('click',event=>{if(event.target===lightbox){const bounds=lightbox.getBoundingClientRect();if(event.clientX<bounds.left||event.clientX>bounds.right||event.clientY<bounds.top||event.clientY>bounds.bottom)lightbox.close();}});
const carousel=document.querySelector('.hero-carousel');
if(carousel){
 const slides=[...carousel.querySelectorAll('[data-slide]')];
 const dots=[...carousel.querySelectorAll('[data-go-to]')];
 const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
 slides.forEach((slide,i)=>{slide.hidden=false;slide.classList.toggle('is-active',i===0);slide.setAttribute('aria-hidden',String(i!==0));});
 let index=0;
 let paused=reducedMotion.matches||new URLSearchParams(location.search).has("editor-preview");
 let hovered=false;
 let timer=null;
 let touchStart=null;
 const canPlay=()=>!paused&&!hovered&&!document.hidden&&!carousel.contains(document.activeElement);
 const schedule=()=>{clearTimeout(timer);timer=null;if(canPlay())timer=setTimeout(()=>show(index+1),5000);};
 const show=next=>{index=(next+slides.length)%slides.length;slides.forEach((slide,i)=>{slide.classList.toggle('is-active',i===index);slide.setAttribute('aria-hidden',String(i!==index));});dots.forEach((dot,i)=>dot.setAttribute('aria-current',String(i===index)));schedule();};
 carousel.querySelectorAll('[data-slide-step]').forEach(button=>button.addEventListener('click',()=>show(index+Number(button.dataset.slideStep))));
 dots.forEach((dot,i)=>dot.addEventListener('click',()=>show(i)));
 carousel.addEventListener('mouseenter',()=>{hovered=true;schedule();});
 carousel.addEventListener('mouseleave',()=>{hovered=false;schedule();});
 carousel.addEventListener('focusin',schedule);
 carousel.addEventListener('focusout',()=>setTimeout(schedule,0));
 carousel.addEventListener('touchstart',event=>{touchStart={x:event.changedTouches[0].clientX,y:event.changedTouches[0].clientY};clearTimeout(timer);},{passive:true});
 carousel.addEventListener('touchend',event=>{if(touchStart){const dx=event.changedTouches[0].clientX-touchStart.x;const dy=event.changedTouches[0].clientY-touchStart.y;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy))show(index+(dx<0?1:-1));else schedule();touchStart=null;}},{passive:true});
 carousel.addEventListener('touchcancel',()=>{touchStart=null;schedule();},{passive:true});
 document.addEventListener('visibilitychange',schedule);
 reducedMotion.addEventListener('change',event=>{paused=event.matches;schedule();});
 schedule();
}
