const $=id=>document.getElementById(id);
let data={version:1,posts:[]},folder=null,currentId=null,image='',dirty=false,imageBusy=false;
const status=message=>$('status').textContent=message;
const today=()=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const value=type=>parts.find(p=>p.type===type).value;return `${value('year')}-${value('month')}-${value('day')}`;};
function validate(value){if(value?.version!==1||!Array.isArray(value.posts)||value.posts.some(p=>!p||typeof p.id!=='string'||typeof p.title!=='string'||typeof p.body!=='string'))throw Error('รูปแบบไฟล์ข่าวไม่ถูกต้อง');return value;}
function preview(){ $('preview-title').textContent=$('title').value||'หัวข้อข่าว';$('preview-meta').textContent=$('category').value+' · '+$('date').value;$('preview-summary').textContent=$('summary').value;$('preview-body').textContent=$('body').value;$('preview-image').hidden=!image;if(image)$('preview-image').src=image;else $('preview-image').removeAttribute('src');}
let newsPage=1;
function list(){const term=$('news-search').value.toLowerCase();const posts=[...data.posts].filter(post=>post.title.toLowerCase().includes(term)).sort((a,b)=>b.date.localeCompare(a.date));const total=Math.max(1,Math.ceil(posts.length/6));newsPage=Math.min(newsPage,total);$('posts').replaceChildren();posts.slice((newsPage-1)*6,newsPage*6).forEach(post=>{const button=document.createElement('button');button.type='button';button.textContent=(post.published?'':'[ยังไม่แสดง] ')+post.title;button.setAttribute('aria-pressed',String(post.id===currentId));button.onclick=()=>{if(dirty&&!confirm('ยังไม่ได้บันทึกข่าวนี้ ต้องการเปลี่ยนข่าวและทิ้งสิ่งที่แก้ไขหรือไม่?'))return;load(post);};$('posts').append(button);});$('news-pagination').replaceChildren();const prev=document.createElement('button');prev.textContent='ก่อนหน้า';prev.disabled=newsPage===1;prev.onclick=()=>{newsPage--;list();};const count=document.createElement('span');count.textContent=`${posts.length} ข่าว · ${newsPage}/${total}`;const next=document.createElement('button');next.textContent='ถัดไป';next.disabled=newsPage===total;next.onclick=()=>{newsPage++;list();};$('news-pagination').append(prev,count,next);}
$('news-search').oninput=()=>{newsPage=1;list();};
$('news-backup').onclick=()=>$('download').click();
function load(post){currentId=post?.id||null;for(const key of ['title','category','date','summary','body'])$(key).value=post?.[key]||(key==='category'?'ข่าวสาร':key==='date'?today():'');$('published').checked=post?.published??true;image=post?.image||'';$('image').value='';dirty=false;preview();list();}
function update(){if(imageBusy)throw Error('กรุณารอรูปภาพประมวลผลเสร็จก่อน');if(!$('editor').reportValidity())return false;currentId=currentId||crypto.randomUUID();const post={id:currentId,title:$('title').value.trim(),category:$('category').value.trim(),date:$('date').value,summary:$('summary').value.trim(),body:$('body').value.trim(),image,published:$('published').checked};if(!post.title||!post.body)throw Error('กรุณากรอกหัวข้อและเนื้อหา');const index=data.posts.findIndex(p=>p.id===currentId);if(index<0)data.posts.push(post);else data.posts[index]=post;list();return true;}
async function save(){if(await window.gddLocal?.available()){await window.gddLocal.save('news',data);dirty=false;status('บันทึกข่าวเรียบร้อย ✓ เว็บบนเครื่องจะอัปเดตอัตโนมัติ');return;}if(!folder)throw Error('เปิดผ่านไฟล์ เปิดแอดมิน.cmd เพื่อบันทึกอัตโนมัติ หรือเลือกโฟลเดอร์ในเมนูตั้งค่า');const permission=await folder.requestPermission({mode:'readwrite'});if(permission!=='granted')throw Error('ยังไม่ได้อนุญาตให้บันทึกไฟล์');const directory=await folder.getDirectoryHandle('content',{create:true});const file=await directory.getFileHandle('news.json',{create:true});const stream=await file.createWritable();await stream.write(JSON.stringify(data,null,2));await stream.close();dirty=false;status('บันทึกแล้ว! รีเฟรชหน้า Home / News เพื่อดูข่าวบนเครื่อง การเผยแพร่ออนไลน์ให้อัปโหลด content/news.json ไปที่โฮสต์');}
$('connect').onclick=async()=>{try{if(!window.showDirectoryPicker)throw Error('เบราว์เซอร์นี้เลือกโฟลเดอร์ไม่ได้ ให้ใช้ Chrome / Edge บนคอม หรือปุ่มนำเข้าและดาวน์โหลดไฟล์ข่าว');if(dirty&&!confirm('มีข่าวที่ยังไม่บันทึก ต้องการเปิดโฟลเดอร์และทิ้งการแก้ไขหรือไม่?'))return;const selected=await showDirectoryPicker({mode:'readwrite'});await selected.getFileHandle('site.js');const directory=await selected.getDirectoryHandle('content');const file=await (await directory.getFileHandle('news.json')).getFile();const next=validate(JSON.parse(await file.text()));folder=selected;data=next;$('download').disabled=false;load(null);status('เชื่อมต่อโฟลเดอร์ '+folder.name+' แล้ว เริ่มเพิ่มข่าวหรือเลือกข่าวเพื่อแก้ไขได้เลย');}catch(error){if(error.name!=='AbortError')status('เปิดโฟลเดอร์ไม่ได้: '+error.message);}};
$('import').onclick=()=>$('import-file').click();
$('import-file').onchange=async event=>{try{const file=event.target.files[0];if(!file)return;if(dirty&&!confirm('ต้องการนำเข้าไฟล์และทิ้งข่าวที่ยังไม่บันทึกหรือไม่?'))return;data=validate(JSON.parse(await file.text()));$('download').disabled=false;folder=null;load(null);status('นำเข้าข่าวแล้ว แก้ไขและดาวน์โหลดไฟล์ news.json ใหม่ไปแทนที่ไฟล์เดิม');}catch(error){status(error.message);}finally{event.target.value='';}};
$('new').onclick=()=>{if(!dirty||confirm('ทิ้งการแก้ไขที่ยังไม่บันทึกและเพิ่มข่าวใหม่หรือไม่?'))load(null);};
$('editor').addEventListener('input',()=>{dirty=true;preview();});
$('editor').onsubmit=async event=>{event.preventDefault();try{if(update())await save();}catch(error){status(error.message);}};
$('download').onclick=()=>{try{if(dirty||(!currentId&&($('title').value.trim()||$('body').value.trim()))){if(!update())return;}const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='news.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);dirty=false;status('ดาวน์โหลดแล้ว นำไฟล์ news.json ไปแทนที่ content/news.json ในโฟลเดอร์เว็บ แล้วอัปโหลดไฟล์นี้ไปที่โฮสต์เมื่อต้องการเผยแพร่');}catch(error){status(error.message);}};
$('delete').onclick=async()=>{if(!currentId){status('เลือกข่าวที่จะลบก่อน');return;}if(!confirm('นำข่าวนี้ออกจากรายการหรือไม่? เก็บไฟล์สำรองไว้ก่อนหากต้องการกู้คืน'))return;const previous=data.posts;data.posts=data.posts.filter(p=>p.id!==currentId);try{if(folder)await save();else{dirty=true;status('นำข่าวออกแล้ว กดดาวน์โหลดไฟล์ข่าวเพื่อบันทึกรายการที่เหลือ');}load(null);}catch(error){data.posts=previous;status('ยังลบไม่สำเร็จ: '+error.message);}};
$('remove-image').onclick=()=>{image='';$('image').value='';dirty=true;preview();};
$('image').onchange=async event=>{const file=event.target.files[0];if(!file)return;imageBusy=true;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('ใช้รูป PNG, JPG หรือ WebP');if(file.size>20*1024*1024)throw Error('รูปใหญ่เกินไป กรุณาใช้รูปไม่เกิน 20 MB');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1400/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();image=canvas.toDataURL('image/webp',.85);dirty=true;preview();status('เตรียมรูปแล้ว กดบันทึกข่าวเมื่อกรอกเสร็จ');}catch(error){status(error.message);}finally{imageBusy=false;}};
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
load(null);
$('download').disabled=true;
fetch('../content/news.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(value=>{data=validate(value);list();$('download').disabled=false;}).catch(()=>{status('โหลดไฟล์ข่าวเดิมไม่ได้ กรุณาเลือกโฟลเดอร์หรือนำเข้าไฟล์ก่อน เพื่อรักษาข่าวเดิม');});

document.addEventListener('gdd:admin-folder',async event=>{if(dirty)return;try{const dir=await event.detail.getDirectoryHandle('content');const file=await(await dir.getFileHandle('news.json')).getFile();data=validate(JSON.parse(await file.text()));folder=event.detail;load(null);status('พร้อมบันทึกข่าว');}catch(error){status(error.message);}});
