(() => {
 const $=id=>document.getElementById(id),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
 const courseCategories=['เริ่มต้นเขียนโค้ด','เกมและโลก 3 มิติ','AI และเทคโนโลยี','สิ่งประดิษฐ์และหุ่นยนต์','เตรียมสอบและพอร์ต'];
 const kinds={photo:'รูปบรรยากาศการเรียน',video:'บรรยากาศการเรียนผ่านวิดีโอ',work:'จากไอเดีย สู่ผลงานจริง'};
 const config={home:{label:'Home',path:'index.html',file:'site'},courses:{label:'คอร์ส',path:'courses/index.html',file:'collections',key:'courses',categories:courseCategories},gallery:{label:'Gallery',path:'gallery/index.html',file:'collections',key:'gallery',categories:Object.keys(kinds)},news:{label:'ข่าว',path:'news/index.html',file:'news',key:'posts',categories:['ข่าวสาร','กิจกรรม','ประกาศ','รางวัลนักเรียน','หลักสูตร']},teachers:{label:'ครู',path:'teachers/coding/index.html',file:'teachers',key:'teachers',categories:['โค้ดดิ้ง','วิชาการ']},about:{label:'About GDD',path:'about/index.html',file:'site'}};
 let previewDevice=innerWidth<600?'mobile':'desktop';let data={},section='news',category='ทั้งหมด',pageNumber=1,editing=null,changed=false,saving=false,imageBusy=0,folder=null,previewTimer,ready=false;const metadata=new Map();
 const status=t=>$('editor-status').textContent=t;
 const imageURL=v=>typeof v==='string'&&/^(assets\/|data:image\/(png|jpeg|webp);base64,)/.test(v)?(v.startsWith('data:')?v:'../'+v):null;
 const safeURL=v=>{try{return /^https?:$/.test(new URL(v,location.href).protocol);}catch{return false;}};
 function youtube(value){try{const u=new URL(value);const id=u.hostname==='youtu.be'?u.pathname.slice(1):['youtube.com','www.youtube.com','youtube-nocookie.com','www.youtube-nocookie.com'].includes(u.hostname)?u.searchParams.get('v')||u.pathname.match(/\/(?:embed|shorts)\/([\w-]+)/)?.[1]:null;return /^[\w-]{11}$/.test(id||'')?'https://www.youtube-nocookie.com/embed/'+id:null;}catch{return null;}}
 function discard(){return !changed||confirm('ยังไม่ได้บันทึก ต้องการออกจากการแก้ไขนี้หรือไม่?');}
 function navigate(name){if(saving||!discard())return;section=name;category='ทั้งหมด';pageNumber=1;editing=null;changed=false;$('search-records').value='';$('edit-form').hidden=true;$('browse-panel').hidden=false;for(const button of $('editor-nav').children)button.setAttribute('aria-pressed',String(button.dataset.section===name));window.scrollTo({top:0});$('section-title').textContent=config[name].label;$('section-eyebrow').textContent='เลือกสิ่งที่ต้องการแก้ไข';$('open-public').href='../'+config[name].path;setPreview(config[name].path);render();}
 function pageItems(){const c=config[section],p=data.site.pages.find(p=>p.path===c.path),doc=metadata.get(c.path),groups=new Map();
  for(const f of p.fields){const node=doc.querySelector(`[data-cms-id="${f.id}"]`);let group=f.group||f.id;const container=node?.closest('.hero-copy,.learning-copy,.page-heading,.section-head');if(container)group='block-'+[...doc.querySelectorAll('.hero-copy,.learning-copy,.page-heading,.section-head')].indexOf(container);if(!groups.has(group))groups.set(group,[]);groups.get(group).push(f);}
  return [...groups].map(([id,fields],index)=>{const node=doc.querySelector(`[data-cms-id="${fields[0].id}"]`),slide=node?.closest('.hero-slide'),branch=node?.closest('.branch-card'),scope=node?.closest('section'),heading=scope?.querySelector('h2')?.textContent.replace(/\s+/g,' ').trim();let cat=slide?'ภาพสไลด์หน้าแรก':branch?'สาขา':node?.closest('.hero-copy')?'ข้อความหน้าแรก':heading||'ข้อความและรูปภาพ';const title=fields.find(f=>f.id.startsWith('branch-name-'))?.value||fields.find(f=>f.type==='text')?.value||(slide?'รูปสไลด์ '+([...doc.querySelectorAll('.hero-slide')].indexOf(slide)+1):fields.find(f=>f.type==='image')?'รูปภาพ '+(index+1):'ปุ่ม / ลิงก์');return {id,title,category:cat,image:fields.find(f=>f.type==='image')?.value,fields,published:!fields.some(f=>f.visible===false),branchIndex:branch?[...doc.querySelectorAll('.branch-card')].indexOf(branch):null};}).concat(p.extras.map(extra=>({...extra,extra:true,category:'ส่วนเนื้อหาที่เพิ่ม'})));
 }
 function items(){const c=config[section];return c.file==='site'?pageItems():data[c.file][c.key].map(item=>({...item,title:item.title||item.name,category:section==='gallery'?item.kind:item.category}));}
 function render(){if(!ready)return;const c=config[section],records=items(),cats=c.categories||[...new Set(records.map(r=>r.category))];$('category-filters').replaceChildren();for(const cat of ['ทั้งหมด',...cats]){const count=cat==='ทั้งหมด'?records.length:records.filter(r=>r.category===cat).length,button=el('button',(kinds[cat]||cat)+' · '+count);button.type='button';button.setAttribute('aria-pressed',String(cat===category));button.onclick=()=>{category=cat;pageNumber=1;render();};$('category-filters').append(button);}
 const term=$('search-records').value.toLowerCase(),filtered=records.filter(r=>(category==='ทั้งหมด'||r.category===category)&&(r.title+' '+(r.summary||r.subjects||r.body||'')).toLowerCase().includes(term)),total=Math.max(1,Math.ceil(filtered.length/6));pageNumber=Math.min(pageNumber,total);$('record-list').replaceChildren();for(const item of filtered.slice((pageNumber-1)*6,pageNumber*6)){const row=el('button',null,'record-row');row.type='button';const src=imageURL(item.image);if(src){const img=el('img',null,'row-photo');img.src=src;img.alt=item.title;row.append(img);}else row.append(el('div',section==='gallery'&&item.kind==='video'?'วิดีโอ':section==='courses'?'คอร์ส':'ข้อความ','row-icon'));const info=el('div',null,'row-info');info.append(el('strong',item.title),el('small',(kinds[item.category]||item.category)+(item.published===false?' · ซ่อนอยู่':'')));row.append(info,el('span','แก้ไข →','row-arrow'));row.onclick=()=>edit(item);$('record-list').append(row);}if(!filtered.length)$('record-list').append(el('p','ยังไม่มีรายการในหมวดนี้ กดเพิ่มด้านบนได้เลย'));$('add-record').textContent=section==='home'||section==='about'?'+ เพิ่มส่วนเนื้อหา':'+ เพิ่ม'+(section==='gallery'?(kinds[category]||'รายการ'):c.label);$('pagination').replaceChildren();for(const [text,step] of [['← ก่อนหน้า',-1],['ถัดไป →',1]]){const b=el('button',text);b.disabled=step<0?pageNumber===1:pageNumber===total;b.onclick=()=>{pageNumber+=step;render();};$('pagination').append(b);if(step===-1)$('pagination').append(el('span',`${filtered.length} รายการ · ${pageNumber} / ${total}`));}status('เลือกแก้ไขได้เลย • รายการแสดงครั้งละ 6 อัน');}
 function input(label,value,set,type='text',options){const wrap=el('label',label),control=el(type==='textarea'?'textarea':options?'select':'input');if(options)for(const option of options){const o=el('option',kinds[option]||option);o.value=option;control.append(o);}else if(type==='textarea')control.rows=label.includes('เนื้อหา')?8:3;else control.type=type;control.value=value||'';control.oninput=()=>{set(control.value);changed=true;queuePreview();};wrap.append(control);$('edit-fields').append(wrap);return control;}
 function checkbox(value,set){const wrap=el('label','แสดงบนเว็บไซต์','checkbox-label'),control=el('input');control.type='checkbox';control.checked=value!==false;control.onchange=()=>{set(control.checked);changed=true;queuePreview();};wrap.prepend(control);$('edit-fields').append(wrap);}
 function image(value,set){const img=el('img',null,'edit-image');const src=imageURL(value);if(src)img.src=src;else img.hidden=true;$('edit-fields').append(img);const file=input('รูปภาพ',null,()=>{},'file');file.accept='image/png,image/jpeg,image/webp';file.onchange=async()=>{const f=file.files[0];if(!f)return;imageBusy++;$('save-record').disabled=true;try{if(f.size>20*1024*1024)throw Error('เลือกรูปไม่เกิน 20 MB');const bitmap=await createImageBitmap(f),canvas=document.createElement('canvas'),scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const result=canvas.toDataURL('image/webp',.85);set(result);img.src=result;img.hidden=false;changed=true;queuePreview();}catch(error){status(error.message);}finally{imageBusy--;$('save-record').disabled=imageBusy>0;}};const remove=el('button','นำรูปออก','back-button');remove.type='button';remove.onclick=()=>{set('');img.hidden=true;file.value='';changed=true;queuePreview();};$('edit-fields').append(remove);}
 function edit(item){const c=config[section];editing=structuredClone(item);editing.isNew=item.isNew??!item.id;editing.id=item.id||crypto.randomUUID();changed=false;$('browse-panel').hidden=true;$('edit-form').hidden=false;$('edit-title').textContent=(editing.isNew?'เพิ่ม ':'แก้ไข ')+(c.file==='site'?'เนื้อหา':section==='gallery'?'รายการ Gallery':c.label);$('edit-fields').replaceChildren();$('delete-record').hidden=c.file==='site'&&!editing.extra||editing.isNew;
 if(c.file==='site'&&!editing.extra){let texts=0;for(const field of editing.fields){if(field.type==='text'){input(texts++===0?'หัวข้อ / ข้อความ':'รายละเอียด',field.value,v=>field.value=v,'textarea');}else if(field.type==='image')image(field.value,v=>field.value=v);else input(field.type==='video'?'ลิงก์ YouTube':'ลิงก์ของปุ่ม',field.value,v=>field.value=v);}
 if(editing.branchIndex!==null&&editing.branchIndex!==undefined){editing.coordinates=structuredClone(data.site.pages.find(p=>p.path===c.path).branches?.[editing.branchIndex]?.coordinates||[]);input('ละติจูดสาขา',editing.coordinates[0],v=>editing.coordinates[0]=Number(v),'number').step='any';input('ลองจิจูดสาขา',editing.coordinates[1],v=>editing.coordinates[1]=Number(v),'number').step='any';}}
 else{const titleKey=section==='teachers'?'name':'title';input(section==='teachers'?'ชื่อครู':'หัวข้อ',editing[titleKey],v=>editing[titleKey]=v).required=true;
 if(c.categories){const key=section==='gallery'?'kind':'category';input('หมวดหมู่',editing[key]||c.categories[0],v=>{editing[key]=v;editing.category=v;if(section==='gallery'){const draft=structuredClone(editing);edit(draft);}if(section==='teachers')setPreview(v==='วิชาการ'?'teachers/academic/index.html':'teachers/coding/index.html');},'text',c.categories);editing[key] ||=c.categories[0];}
 if(section==='news'){input('วันที่ข่าว',editing.date,v=>editing.date=v,'date');input('คำอธิบายบนการ์ด',editing.summary,v=>editing.summary=v,'textarea');input('เนื้อหาข่าว',editing.body,v=>editing.body=v,'textarea').required=true;}
 else if(section==='teachers'){input('ชื่อจริง (ไม่บังคับ)',editing.fullName,v=>editing.fullName=v);input('วิชาที่สอน',editing.subjects,v=>editing.subjects=v).required=true;input('แนะนำครู / ประสบการณ์',editing.bio,v=>editing.bio=v,'textarea');}
 else if(section==='courses'){input('คำอธิบายบนการ์ดคอร์ส',editing.summary,v=>editing.summary=v,'textarea');input('รายละเอียดคอร์ส / สิ่งที่จะได้เรียน',editing.body,v=>editing.body=v,'textarea');}
 else input(section==='gallery'?'รายละเอียด / เจ้าของผลงาน':'รายละเอียด',editing.body,v=>editing.body=v,'textarea');
 if(section==='gallery'||editing.extra)input(section==='gallery'?(editing.kind==='video'?'ลิงก์วิดีโอ YouTube (วางลิงก์จากแถบที่อยู่)':'ลิงก์เว็บไซต์ผลงาน (ไม่บังคับ)'):'ลิงก์ของปุ่ม (ไม่บังคับ)',editing.url||editing.link,v=>{if(editing.extra)editing.link=v;else editing.url=v;});
 if(!(section==='gallery'&&editing.kind==='video'))image(editing.image,v=>editing.image=v);if(section==='courses'){editing.posters ||= [];const heading=el('h3','รูปหลักสูตรเพิ่มเติม');$('edit-fields').append(heading);const addPoster=()=>{const poster={title:'',image:''};editing.posters.push(poster);posterFields(poster);changed=true;};const posterFields=poster=>{input('ชื่อรูปหลักสูตร',poster.title,v=>poster.title=v);image(poster.image,v=>poster.image=v);};for(const poster of editing.posters)posterFields(poster);const add=el('button','+ เพิ่มรูปหลักสูตร','back-button');add.type='button';add.onclick=addPoster;$('edit-fields').append(add);}}
 if(section==='courses'){const wrap=el('label','แนะนำคอร์สนี้บน Home (แสดงสูงสุด 3 คอร์ส)','checkbox-label'),box=el('input');box.type='checkbox';box.checked=editing.featured===true;box.onchange=()=>{editing.featured=box.checked;changed=true;queuePreview();};wrap.prepend(box);$('edit-fields').append(wrap);}checkbox(editing.published,v=>editing.published=v);let path=c.path;if(section==='news')path='news/article/index.html?id='+encodeURIComponent(editing.id);if(section==='courses')path='courses/article/index.html?id='+encodeURIComponent(editing.id);if(section==='teachers')path=editing.category==='วิชาการ'?'teachers/academic/index.html':'teachers/coding/index.html';setPreview(path);$('preview-caption').textContent='ตัวอย่างร่าง • ยังไม่ได้บันทึก';window.scrollTo({top:0});queuePreview();}
 function updated(source){const c=config[section],next=structuredClone(source);if(!editing)return next;if(c.file==='site'){const p=next.pages.find(p=>p.path===c.path);if(editing.extra){const record={id:editing.id,title:editing.title||'',body:editing.body||'',image:editing.image||'',link:editing.link||'',linkLabel:'ดูรายละเอียด',published:editing.published};const i=p.extras.findIndex(x=>x.id===editing.id);if(i<0)p.extras.push(record);else p.extras[i]=record;}else{for(const f of editing.fields){const target=p.fields.find(x=>x.id===f.id);if(target)Object.assign(target,f,{visible:editing.published});}if(editing.coordinates&&p.branches?.[editing.branchIndex])p.branches[editing.branchIndex].coordinates=editing.coordinates;}}else{const record=structuredClone(editing);for(const key of ['isNew','fields','extra','branchIndex','coordinates'])delete record[key];if(section==='teachers')delete record.title;if(section==='gallery')delete record.category;const i=next[c.key].findIndex(x=>x.id===record.id);if(i<0)next[c.key].unshift(record);else next[c.key][i]=record;}return next;}
 function queuePreview(){clearTimeout(previewTimer);previewTimer=setTimeout(sendPreview,180);}
 function sendPreview(){if(!ready)return;const preview={type:'gdd-preview',...data,focus:editing?.fields?.[0]?.id,recordId:editing?.id};if(editing)preview[config[section].file]=updated(data[config[section].file]);$('website-preview').contentWindow?.postMessage(preview,location.origin);}
 function setPreview(path){const url='../'+path+(path.includes('?')?'&':'?')+'editor-preview=1';if($('website-preview').getAttribute('src')!==url)$('website-preview').src=url;else queuePreview();}
 async function persist(file,value){if(await window.gddLocal?.available())return window.gddLocal.save(file,value);if(!window.showDirectoryPicker)throw Error('บันทึกบนเครื่อง: เปิดไฟล์ เปิดแอดมิน.cmd จากโฟลเดอร์ WebGDD');if(!folder){folder=await showDirectoryPicker({mode:'readwrite'});await folder.getFileHandle('site-content.js');}const dir=await folder.getDirectoryHandle('content'),h=await dir.getFileHandle(file+'.json'),w=await h.createWritable();await w.write(JSON.stringify(value,null,2));await w.close();}
 async function save(remove=false){if(!editing||saving||imageBusy)return;const c=config[section];saving=true;$('save-record').disabled=true;$('delete-record').disabled=true;status('กำลังบันทึก…');try{if(!remove){if(section==='gallery'&&editing.kind==='video'&&!youtube(editing.url))throw Error('วางลิงก์วิดีโอ YouTube ที่ถูกต้อง เช่น https://youtu.be/...');if(section==='gallery'&&editing.kind!=='video'&&!editing.image)throw Error('เลือกรูปภาพก่อนบันทึก');if(editing.coordinates&&(!editing.coordinates.every(Number.isFinite)||Math.abs(editing.coordinates[0])>90||Math.abs(editing.coordinates[1])>180))throw Error('พิกัดสาขาไม่ถูกต้อง');if(editing.fields)for(const f of editing.fields.filter(f=>f.type==='video')){const url=youtube(f.value);if(!url)throw Error('ลิงก์ YouTube ไม่ถูกต้อง');f.value=url;}}
 if(section==='gallery'&&editing.url&&!safeURL(editing.url))throw Error('ลิงก์เว็บไซต์ต้องขึ้นต้นด้วย https:// หรือ http://');
 const latest=await(await fetch('../content/'+c.file+'.json',{cache:'no-store'})).json();let next;if(remove){next=structuredClone(latest);if(c.file==='site'){const p=next.pages.find(p=>p.path===c.path);p.extras=p.extras.filter(x=>x.id!==editing.id);}else next[c.key]=next[c.key].filter(x=>x.id!==editing.id);}else next=updated(latest);await persist(c.file,next);data[c.file]=next;changed=false;editing=null;$('edit-form').hidden=true;$('browse-panel').hidden=false;setPreview(c.path);render();sendPreview();window.scrollTo({top:0});status('บันทึกเรียบร้อย ✓ เว็บบนเครื่องอัปเดตภายใน 15 วินาที');$('preview-caption').textContent='ตัวอย่างจากข้อมูลที่บันทึกแล้ว';}catch(error){if(error.name!=='AbortError')status(error.message);}finally{saving=false;$('save-record').disabled=false;$('delete-record').disabled=false;}}
 $('edit-form').onsubmit=e=>{e.preventDefault();save();};$('delete-record').onclick=()=>{if(confirm('ลบรายการนี้หรือไม่? ฉบับก่อนหน้าจะสำรองไว้เมื่อเปิดผ่านตัวเปิดแอดมิน'))save(true);};$('back-to-list').onclick=()=>{if(saving||!discard())return;editing=null;changed=false;$('edit-form').hidden=true;$('browse-panel').hidden=false;setPreview(config[section].path);render();sendPreview();};$('search-records').oninput=()=>{pageNumber=1;render();};$('add-record').onclick=()=>{const c=config[section];edit(c.file==='site'?{extra:true,title:'',body:'',image:'',link:'',published:true}:{[section==='teachers'?'name':'title']:'',category:category==='ทั้งหมด'?c.categories[0]:category,kind:section==='gallery'?(category==='ทั้งหมด'?'photo':category):undefined,date:new Date().toISOString().slice(0,10),published:true,image:'',body:'',summary:''});};function sizePreview(){const frame=$('website-preview'),width=previewDevice==='mobile'?390:1100,available=frame.parentElement.clientWidth-20,scale=Math.min(1,available/width);frame.style.width=width+'px';frame.style.minWidth=width+'px';frame.style.height=(650/scale)+'px';frame.style.zoom=String(scale);for(const name of ['desktop','mobile'])$('preview-'+name).setAttribute('aria-pressed',String(name===previewDevice));}window.addEventListener('resize',sizePreview);$('website-preview').onload=()=>{sizePreview();sendPreview();};for(const device of ['desktop','mobile'])$('preview-'+device).onclick=()=>{previewDevice=device;sizePreview();for(const name of ['desktop','mobile'])$('preview-'+name).setAttribute('aria-pressed',String(name===device));};window.addEventListener('beforeunload',e=>{if(changed){e.preventDefault();e.returnValue='';}});
 for(const [name,c] of Object.entries(config)){const b=el('button',c.label);b.type='button';b.dataset.section=name;b.onclick=()=>{if(ready)navigate(name);};$('editor-nav').append(b);}
 Promise.all(['site','news','teachers','collections'].map(async file=>{const r=await fetch('../content/'+file+'.json',{cache:'no-store'});if(!r.ok)throw Error('โหลด '+file+' ไม่ได้ กรุณาเปิดโฟลเดอร์ WebGDD ให้ถูกต้อง');data[file]=await r.json();})).then(()=>Promise.all(['index.html','about/index.html'].map(async path=>{const html=await(await fetch('../'+path)).text();metadata.set(path,new DOMParser().parseFromString(html,'text/html'));}))).then(()=>{ready=true;navigate('news');}).catch(error=>status(error.message));
})();
